### PR TITLE
Extend datasets for public and inner using

### PR DESCRIPTION
**Pull request by PetrovKP**
1. Add support loader datasets
2. Extend datasets for gisette, a9a, ijcnn and skin-segmentation for SVM algorithm

### CODE REVIEW

**Comment by PetrovKP** [comment]
@SmirnovEgorRu , @PivovarA , @Alexsandruss  What do you think about this format for receiving datasets?

**Comment by Alexsandruss** [comment]
There must be an option to load dataset directly without saving to csv.

**Comment by PetrovKP** [comment]
@Alexsandruss 
> There must be an option to load dataset directly without saving to csv.

What is it for? When downloading, the original datasets are stored in cache folders.

**Comment by Alexsandruss** [comment]
> > There must be an option to load dataset directly without saving to csv.
> 
> What is it for? When downloading, the original datasets are stored in cache folders.

Some datasets are too heavy to process them, save to csv and read from same csv. Option to load directly (without or with csv saving) is needed to reduce benchmarks running time.

**Comment by PetrovKP** [comment]
Implemented here https://github.com/IntelPython/scikit-learn_bench/pull/44

**Pull request closed without merging**
